# -*- coding: utf-8 -*-
"""Project 14 Parkinson's Disease SVM-SVC

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1938L3yxzOcr4hlNS-YvKn_dTLL7O58_m

Importing the dependencies
"""

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn import svm
from sklearn.metrics import accuracy_score

"""Data Collections"""

parkinsons_data = pd.read_csv('/content/parkinsons.csv')

parkinsons_data.head()

parkinsons_data.shape

parkinsons_data.info()

parkinsons_data.describe()

parkinsons_data.isnull().sum()

parkinsons_data.groupby('status').mean()

"""Data Preprocessing

"""

X = parkinsons_data.drop(columns=['name','status'],axis=1)
Y = parkinsons_data['status']

"""splitting the data to test and train"""

X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,random_state=2)

scaler = StandardScaler()

scaler.fit(X_train)

X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

model = svm.SVC(kernel='linear')

model.fit(X_train,Y_train)

"""Model evaluation"""

X_train_prediction = model.predict(X_train)

training_data_accuracy = accuracy_score(X_train_prediction,Y_train)

print(training_data_accuracy)

X_test_prediction = model.predict(X_test)

testing_data_accuracy = accuracy_score(X_test_prediction,Y_test)

print(testing_data_accuracy)

"""Building a Predictive System"""

input_data = (162.56800,198.34600,77.63000,0.00502,0.00003,0.00280,0.00253,0.00841,0.01791,0.16800,0.00793,0.01057,0.01799,0.02380,0.01170,25.67800,0.427785,0.723797,-6.635729,0.209866,1.957961,0.135242)
input_data_as_numpy_array = np.asarray(input_data)

reshaped_data = input_data_as_numpy_array.reshape(1,-1)

standard_data_ = scaler.transform(reshaped_data)

prediction = model.predict(standard_data_)
print(prediction)

